### ISSUE TITLE
next steps?

### ISSUE THREAD

**Issue by mrose17** [danopia/sshd.js#1]
hi! can you give me a sense as to what your plans are? i was thinking of writing a module with similar functionality. if you're not going to be touching the code for a while, i'll probably fork and get to it. but, if you're planning on making a bunch of updates soon, i should wait.

thanks,

/mtr

**Comment by danopia** [comment]
I have no current plans to resume this project. There's a lot of cool stuff that can be done with ssh, but I don't have time to properly execute most of them. My next step would be implementing additional auth algorithms, as lower-grade clients (e.g. android clients) do not support SHA2 algorithms, which are the only ones currently implemented.

Feel free to fork :)

**Comment by mrose17** [comment]
thanks!  I'll give it a shot...  first up, jshint(sorry!) and callbacks for auth and commands...

I'll drop you a note later on...

**Comment by danopia** [comment]
If you have questions about the SSH protocol or how I implement it, feel free to ask. I did a bunch of research and RFC reading to do this project

**Comment by mrose17** [comment]
many thanks! i plan on taking you up on that offer in the next few days.

best,

/mtr
