### ISSUE TITLE
your advice? (long-lived issue...)

### ISSUE THREAD

**Issue by mrose17** [danopia/sshd.js#2]
hi. i'm about half way through my first pass. while i am waiting on iTunes connect (for another project), i thought i'd ask you an architectural question:

i'd like the server to be able to advertise multiple keys, or advertise a particular key depending on who the client is.

my understanding of the ssh message exchange indicates this isn't possible: the server has to bind its key upon receipt of a KEXINIT or KEX_DH_GEX_INIT and this occurs well before a USERAUTH_REQUEST is sent.

furthermore, there isn't a way to advertise multiple keys.

do you agree? any tricks we might pull here?

thanks,

/mtr

**Comment by mrose17** [comment]
ok, i've done a push to my fork of the repository and am seeking your comments:

```
https://github.com/mrose17/sshd.js
```

here are the changes:

first, i ran it through jshint and did a fair amount of reformatting. sorry about that. i know that formatting is a very personal issue, but my eyes are very old and i need a certain layout in order to grok the code better. mea culpa.

second, i have added pre-authorization, authentication, and channel creation callbacks to move this logic from the sshd.js module.
1. when a SERVICE_REQUEST comes in, the caller can provide a callback to look at the service and decide whether to allow it. the default callback says "ssh-userauth" is OK and that's it. the reason this is a callback is because things like netconf over ssh (and my own protocol) request a different service before doing the channel open.

the callback can either say OK or give a reason why the service isn't allowed in a SERVICE_DISCONNECT message.
1. when a USERAUTH_REQUEST comes in, the relevant parameters are gathered based on the method, and then the callback decides what to send back USERAUTH_SUCCESS, USERAUTH_FAILURE, USERAUTH_60 or USERAUTH_BANNER. i believe that the logic that invokes the callback is sufficient to do what you wanted to dowith the inline code, although i couldn't quite follow it all.
2. when a CHANNEL_OPEN comes in, a callback is invoked to get a callback that will handle events for the channel.  the same is true for CHANNEL_REQUEST and then subsequent data.

let me know what you think!

thanks,

/mtr

**Comment by danopia** [comment]
Advertising different keys is definitely possible given a custom client. Assuming you want to use "real" clients though, I don't think that enough information is passed on at the KEX point to make a decision like that - most of it is intentionally transferred AFTER encryption is set up, for obvious reasons.

Does your auth callback system support interactive auth? Because that's where a lot of the cool stuff can be done auth-wise :) and yes, the code is currently spaghetti. Note that this is basically one large file :P

Rest of that sounds cool. I'd like to see a sample/demo application for what you're working on. :)

**Comment by mrose17** [comment]
thanks. interactive auth may be the place to put the magic. i should know more in a few days.

in terms of the "one big file" ... true, however, there's a strong skeleton, which is why i'm starting with your code, so i don't have to rebuild that....
